services:
  planka-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: planka-dev
    pull_policy: never
    command: ["bash", "-c", "npm install && npm run db:init && npm start"]
    restart: on-failure
    volumes:
      - ./server:/app
    ports:
      - 1337:1337
    environment:
      - BASE_URL=http://localhost:1337
      - DATABASE_URL=postgresql://postgres@postgres/planka
      - SECRET_KEY=notsecretkey

    depends_on:
      postgres:
        condition: service_healthy

  planka-client:
    image: planka-dev
    pull_policy: never
    command: ["bash", "-c", "npm install && npx vite --host"]
    restart: on-failure
    volumes:
      - ./client:/app
    ports:
      - 3000:3000

  postgres:
    image: postgres:16-alpine
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-planka} && psql -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-planka} -c 'SELECT 1'",
        ]
      interval: 3s
      timeout: 5s
      retries: 15
      start_period: 10s

volumes:
  db-data:
